version: '3.3'
services:
  client:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/fedn-client:develop"
    build:
      context: ${PWD}
      dockerfile: ${PWD}/components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "sleep 10 && fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ${PWD}/config:/app/config
      - ${PWD}/test/${EXAMPLE}/data:/app/data
