version: '3.3'

services:

  combiner:
    image: "scaleoutsystems/fedn-combiner:master"
    environment:
      - PYTHONUNBUFFERED=0
      - GET_HOSTS_FROM=dns
    working_dir: /app/client
    command: sh -c "sleep 5 && fedn run combiner -in ./config/settings-combiner.yaml"
    volumes:
      - ${PWD}/config:/app/client/config
      - ${PWD}/tmp/c1-models:/tmp/models
    ports:
      - 12080:12080
